name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: feat/overlay-scripting
          path: modengine_install
          repo: soulsmods/modengine2

      - name: 'Build with CMake'
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/src/modengine_extension/CMakeLists.txt'
          cmakeAppendedArgs: '-G "Unix Makefiles"
            "-DSTEAMWORKS_SDK=${{ github.workspace }}/vendor/SteamworksSDKCI/steamworks_sdk"
            "-DCMAKE_PREFIX_PATH=${{ github.workspace }}/modengine_install/share/cmake"'
          useVcpkgToolchainFile: false
          buildDirectory: '${{ runner.workspace }}/build/modengine_extension'



